version: '3.3'

services:
#db name
  db:
    image: postgres:latest
    container_name: ilumeo
    restart: unless-stopped
    # command: [--auth]
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      # POSTGRES_DB: postgres
    ports:
      - 5432:5432
    volumes:
      - ./db-data:/data/db 
